#!/usr/bin/env python3
"""
Bakes the UI/UX Pro Max databases into a TypeScript module the browser can use.

The skill itself is a design-time tool: CSV files searched by a Python script.
A deployed page has neither, so the data it needs is extracted here, at build
time, into `src/lib/uipm-data.ts`. Re-run after updating the skill package:

    python3 scripts/build-uipm-data.py

Source: https://github.com/nextlevelbuilder/ui-ux-pro-max-skill (MIT).
"""

import csv
import json
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parent.parent
DATA = ROOT / '.claude/skills/ui-ux-pro-max/data'
OUT = ROOT / 'src/lib/uipm-data.ts'


def rows(name: str) -> list[dict]:
    with (DATA / name).open(encoding='utf-8') as handle:
        return list(csv.DictReader(handle))


def families(url: str) -> list[str]:
    """Pull font family names out of a Google Fonts css2 URL."""
    out = []
    for match in re.findall(r'family=([^:&]+)', url or ''):
        out.append(match.replace('+', ' '))
    return out


def to_hex(value: str, over: str) -> str:
    """
    Normalise a colour to #rrggbb. Some rows carry a translucent border such as
    `'rgba(255,255,255,0.08)'` (quotes included); those get composited over the
    row's own background so the generator, which mixes hex, keeps working.
    """
    raw = (value or '').strip().strip('\'"').strip()

    if re.fullmatch(r'#[0-9A-Fa-f]{6}', raw):
        return raw.lower()
    if re.fullmatch(r'#[0-9A-Fa-f]{3}', raw):
        return '#' + ''.join(c * 2 for c in raw[1:]).lower()

    rgba = re.fullmatch(r'rgba?\(\s*([\d.]+)[,\s]+([\d.]+)[,\s]+([\d.]+)(?:[,\s/]+([\d.]+))?\s*\)', raw)
    if rgba:
        r, g, b = (float(rgba.group(i)) for i in (1, 2, 3))
        alpha = float(rgba.group(4)) if rgba.group(4) else 1.0
        base = to_hex(over, '#ffffff') if over != raw else '#ffffff'
        br, bg, bb = (int(base[i:i + 2], 16) for i in (1, 3, 5))
        mixed = (
            round(br + (r - br) * alpha),
            round(bg + (g - bg) * alpha),
            round(bb + (b - bb) * alpha),
        )
        return '#%02x%02x%02x' % mixed

    raise ValueError(f'couleur non reconnue: {value!r}')


def keywords(*values: str) -> list[str]:
    """Lowercase keyword bag used for matching a brief against a row."""
    bag: list[str] = []
    for value in values:
        for word in re.split(r'[,/;()]|\s+', (value or '').lower()):
            word = word.strip('-.& ')
            if len(word) > 2 and word not in bag:
                bag.append(word)
    return bag[:26]


palettes = []
for row in rows('colors.csv'):
    # Their token names map onto the generator's ramp: Background is the page
    # ground, Card the raised surface, Primary the brand accent.
    ground = to_hex(row['Background'], '#ffffff')
    palettes.append(
        {
            'id': f"uipm-{row['No']}",
            'label': row['Product Type'],
            'ground': ground,
            'raised': to_hex(row['Card'], ground),
            'ink': to_hex(row['Foreground'], ground),
            'muted': to_hex(row['Muted Foreground'], ground),
            'line': to_hex(row['Border'], ground),
            'accent': to_hex(row['Primary'], ground),
            'accentInk': to_hex(row['On Primary'], ground),
            'keywords': keywords(row['Product Type'], row.get('Notes', '')),
        }
    )

pairs = []
for row in rows('typography.csv'):
    url = row.get('Google Fonts URL', '')
    pairs.append(
        {
            'id': f"pair-{row['No']}",
            'label': row['Font Pairing Name'],
            'category': row['Category'],
            'heading': row['Heading Font'],
            'body': row['Body Font'],
            'googleUrl': url,
            'googleFamilies': families(url),
            'keywords': keywords(row['Mood/Style Keywords'], row['Best For']),
        }
    )

# Only the fonts actually referenced by a pairing are worth carrying.
used = {name for pair in pairs for name in (pair['heading'], pair['body'])}
fallbacks = {}
for row in rows('google-fonts.csv'):
    if row['Family'] in used:
        category = (row['Category'] or '').lower()
        if 'mono' in category:
            generic = 'monospace'
        elif 'handwriting' in category:
            generic = 'cursive'
        elif 'serif' in category and 'sans' not in category:
            generic = 'serif'
        else:
            generic = 'sans-serif'
        fallbacks[row['Family']] = generic

banner = (
    '/*\n'
    ' * Generated by scripts/build-uipm-data.py — do not edit by hand.\n'
    ' *\n'
    ' * Databases from the UI/UX Pro Max skill (MIT), baked in at build time so\n'
    ' * the generator can use them in the browser, where the skill\'s Python\n'
    ' * search tool cannot run.\n'
    ' * Source: https://github.com/nextlevelbuilder/ui-ux-pro-max-skill\n'
    ' */\n\n'
)

types = '''export interface UipmPalette {
  id: string
  label: string
  ground: string
  raised: string
  ink: string
  muted: string
  line: string
  accent: string
  accentInk: string
  keywords: string[]
}

export interface UipmFontPair {
  id: string
  label: string
  category: string
  heading: string
  body: string
  googleUrl: string
  googleFamilies: string[]
  keywords: string[]
}

'''

body = (
    banner
    + types
    + f'export const UIPM_PALETTES: UipmPalette[] = {json.dumps(palettes, ensure_ascii=False, indent=2)}\n\n'
    + f'export const UIPM_FONT_PAIRS: UipmFontPair[] = {json.dumps(pairs, ensure_ascii=False, indent=2)}\n\n'
    + '/** Generic family to fall back on while a Google font loads, or if it fails. */\n'
    + f'export const FONT_FALLBACK: Record<string, string> = {json.dumps(fallbacks, ensure_ascii=False, indent=2, sort_keys=True)}\n'
)

OUT.write_text(body, encoding='utf-8')
print(f'{len(palettes)} palettes, {len(pairs)} associations, {len(fallbacks)} polices -> {OUT.relative_to(ROOT)}')
print(f'{OUT.stat().st_size / 1024:.0f} Ko')
